export {
  getSite,
  getProfile,
  getExperiences,
  getSkills,
  getCredentials,
  getProjects,
  getProject,
  getStats,
  getTestimonials,
  getSitemap,
  getRedirects,
  getSeoPage,
  getGithub,
  type ProfileData,
} from "./client";

export {
  siteSchema,
  profileSchema,
  experienceSchema,
  skillGroupSchema,
  educationSchema,
  certificateSchema,
  projectCardSchema,
  projectDetailSchema,
  statsSchema,
  sitemapSchema,
  redirectSchema,
  testimonialSchema,
  githubSchema,
  seoPageSchema,
  envelopeSchema,
} from "./schemas";

export type {
  Site,
  Experience,
  SkillGroup,
  Skill,
  Education,
  Certificate,
  ProjectCard,
  ProjectDetail,
  ProofStats,
  SitemapEntry,
  Redirect,
  Testimonial,
  GithubData,
  SeoPage,
  LocaleMeta,
  FeatureFlags,
  SocialLink,
} from "./schemas";

export { TAGS, projectTag, articleTag } from "./tags";
